os:
  - linux

language: php

php:
  - '7.2'

services:
  - mysql

before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.travis .env
  - mysql -e 'create database testing_db;'
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - nvm install 7.7.1
  - npm install npm@latest -g
  - npm install -g jshint
  - php artisan key:generate
  - php artisan migrate --seed

script:
  - vendor/bin/phpunit --coverage-text
  - phpcs --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers
  - npm run production
